server:
    port: 8080
    servlet:
        context-path: /sosikbot
spring:
    application:
        name: sosikbot

    # DB 설정
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Abcd1234!
        url: jdbc:mysql://127.0.0.1:3306/sosikbot
        #password: 1234
        #url: jdbc:mysql://127.0.0.1:3306/sosikbottest
        username: root

    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false
        
    # jpa 설정
    jpa:
        database: mysql
        open-in-view: false
        show_sql: true
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            format_sql: true
            type:
                json_format_mapper: org.hibernate.type.format.jackson.JacksonJsonFormatMapper
                
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# SoSikbot
BOT_TOKEN_KEY: 7969033732:AAE0lV7IQB9x79PZ9x8msmu7Na2O50-NEac
BOT_NAME: SOSIK_bot

# ImTestBot
#BOT_TOKEN_KEY: 8103901295:AAHtijiVJ7avpDDI5WXjoIio6JQkaVv2Om8
#BOT_NAME: IM_CoinTest_bot
